version: "3"
services:
  frontend:
    container_name: ngixreactapp
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - sub-network
    ports:
      - 80:80
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - sub-network
    ports:
      - 3001:3001
networks:
  sub-network:
